### ISSUE TITLE
How to add ip familia to ignore.ip.list

### ISSUE THREAD

**Issue by freebet** [jgmdev/ddos-deflate#42] opened 2018-03-04 23:44 UTC
Hi,

I'm wondering, how to add ip familia to ignore.ip.list.

Like
123,225,567,34
123,225,567,35
123,225,567,36
and more ip have in a service, i dont know all ips, for this i can add as familia to  ignore.ip.list like "123,225.*", possible?

**Comment by jgmdev** [comment] 2018-11-06 19:16
Implemented and duplicate of #6

**Closed by jgmdev** 2018-11-06 19:16 UTC
