### ISSUE TITLE
Subnet support

### ISSUE THREAD

**Issue by angristan** [jgmdev/ddos-deflate#25] opened 2016-06-05 19:10 UTC
Hello,

I have to whitelist [Cloudflare's IPs](https://www.cloudflare.com/ips/) on ddos-deflate, otherwise they get banned.

But all the IPs are in this form : 103.21.244.0/22 and the script is not compatible with that :(

**Comment by jgmdev** [comment] 2018-11-06 19:09
Implemented and duplicate of #6

**Closed by jgmdev** 2018-11-06 19:09 UTC
